//! Pinned Minecraft 26.3 combat roster. Aquatic, neutral and command-only
//! creatures use custom arena aggression; this is not vanilla spawning/AI.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Family {
    Bee,
    Blaze,
    Breeze,
    Creaking,
    Creeper,
    Dolphin,
    Dragon,
    Ghast,
    Guardian,
    Hoglin,
    Humanoid,
    Illager,
    Mount,
    Nautilus,
    Phantom,
    Quadruped,
    Rabbit,
    Ravager,
    Shulker,
    Silverfish,
    Slime,
    SnowGolem,
    Spider,
    TallHumanoid,
    Vex,
    Warden,
    Witch,
    Wither,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Kind {
    Zombie,
    BabyZombie,
    Husk,
    BabyHusk,
    Drowned,
    BabyDrowned,
    ZombieVillager,
    BabyZombieVillager,
    Skeleton,
    Stray,
    Bogged,
    Parched,
    WitherSkeleton,
    Creeper,
    ChargedCreeper,
    Spider,
    CaveSpider,
    Slime,
    MagmaCube,
    Enderman,
    Blaze,
    Breeze,
    Ghast,
    Phantom,
    Vex,
    Witch,
    Pillager,
    Vindicator,
    Evoker,
    Illusioner,
    Ravager,
    Hoglin,
    BabyHoglin,
    Zoglin,
    BabyZoglin,
    Piglin,
    BabyPiglin,
    PiglinBrute,
    ZombifiedPiglin,
    BabyZombifiedPiglin,
    Guardian,
    ElderGuardian,
    Shulker,
    Silverfish,
    Endermite,
    Creaking,
    Warden,
    Dragon,
    Wither,
    Giant,
    KillerBunny,
    Bee,
    Wolf,
    PolarBear,
    Panda,
    Llama,
    TraderLlama,
    Goat,
    IronGolem,
    SnowGolem,
    Dolphin,
    Pufferfish,
    CamelHusk,
    ZombieNautilus,
    CoralZombieNautilus,
    ZombieHorse,
    SulfurCube,
}
impl Kind {
    pub const ALL: &'static [Kind] = &[
        Kind::Zombie,
        Kind::BabyZombie,
        Kind::Husk,
        Kind::BabyHusk,
        Kind::Drowned,
        Kind::BabyDrowned,
        Kind::ZombieVillager,
        Kind::BabyZombieVillager,
        Kind::Skeleton,
        Kind::Stray,
        Kind::Bogged,
        Kind::Parched,
        Kind::WitherSkeleton,
        Kind::Creeper,
        Kind::ChargedCreeper,
        Kind::Spider,
        Kind::CaveSpider,
        Kind::Slime,
        Kind::MagmaCube,
        Kind::Enderman,
        Kind::Blaze,
        Kind::Breeze,
        Kind::Ghast,
        Kind::Phantom,
        Kind::Vex,
        Kind::Witch,
        Kind::Pillager,
        Kind::Vindicator,
        Kind::Evoker,
        Kind::Illusioner,
        Kind::Ravager,
        Kind::Hoglin,
        Kind::BabyHoglin,
        Kind::Zoglin,
        Kind::BabyZoglin,
        Kind::Piglin,
        Kind::BabyPiglin,
        Kind::PiglinBrute,
        Kind::ZombifiedPiglin,
        Kind::BabyZombifiedPiglin,
        Kind::Guardian,
        Kind::ElderGuardian,
        Kind::Shulker,
        Kind::Silverfish,
        Kind::Endermite,
        Kind::Creaking,
        Kind::Warden,
        Kind::Dragon,
        Kind::Wither,
        Kind::Giant,
        Kind::KillerBunny,
        Kind::Bee,
        Kind::Wolf,
        Kind::PolarBear,
        Kind::Panda,
        Kind::Llama,
        Kind::TraderLlama,
        Kind::Goat,
        Kind::IronGolem,
        Kind::SnowGolem,
        Kind::Dolphin,
        Kind::Pufferfish,
        Kind::CamelHusk,
        Kind::ZombieNautilus,
        Kind::CoralZombieNautilus,
        Kind::ZombieHorse,
        Kind::SulfurCube,
    ];
    pub fn registry_id(self) -> &'static str {
        match self {
            Self::Zombie => "zombie",
            Self::BabyZombie => "zombie",
            Self::Husk => "husk",
            Self::BabyHusk => "husk",
            Self::Drowned => "drowned",
            Self::BabyDrowned => "drowned",
            Self::ZombieVillager => "zombie_villager",
            Self::BabyZombieVillager => "zombie_villager",
            Self::Skeleton => "skeleton",
            Self::Stray => "stray",
            Self::Bogged => "bogged",
            Self::Parched => "parched",
            Self::WitherSkeleton => "wither_skeleton",
            Self::Creeper => "creeper",
            Self::ChargedCreeper => "creeper",
            Self::Spider => "spider",
            Self::CaveSpider => "cave_spider",
            Self::Slime => "slime",
            Self::MagmaCube => "magma_cube",
            Self::Enderman => "enderman",
            Self::Blaze => "blaze",
            Self::Breeze => "breeze",
            Self::Ghast => "ghast",
            Self::Phantom => "phantom",
            Self::Vex => "vex",
            Self::Witch => "witch",
            Self::Pillager => "pillager",
            Self::Vindicator => "vindicator",
            Self::Evoker => "evoker",
            Self::Illusioner => "illusioner",
            Self::Ravager => "ravager",
            Self::Hoglin => "hoglin",
            Self::BabyHoglin => "hoglin",
            Self::Zoglin => "zoglin",
            Self::BabyZoglin => "zoglin",
            Self::Piglin => "piglin",
            Self::BabyPiglin => "piglin",
            Self::PiglinBrute => "piglin_brute",
            Self::ZombifiedPiglin => "zombified_piglin",
            Self::BabyZombifiedPiglin => "zombified_piglin",
            Self::Guardian => "guardian",
            Self::ElderGuardian => "elder_guardian",
            Self::Shulker => "shulker",
            Self::Silverfish => "silverfish",
            Self::Endermite => "endermite",
            Self::Creaking => "creaking",
            Self::Warden => "warden",
            Self::Dragon => "ender_dragon",
            Self::Wither => "wither",
            Self::Giant => "giant",
            Self::KillerBunny => "rabbit",
            Self::Bee => "bee",
            Self::Wolf => "wolf",
            Self::PolarBear => "polar_bear",
            Self::Panda => "panda",
            Self::Llama => "llama",
            Self::TraderLlama => "trader_llama",
            Self::Goat => "goat",
            Self::IronGolem => "iron_golem",
            Self::SnowGolem => "snow_golem",
            Self::Dolphin => "dolphin",
            Self::Pufferfish => "pufferfish",
            Self::CamelHusk => "camel_husk",
            Self::ZombieNautilus => "zombie_nautilus",
            Self::CoralZombieNautilus => "zombie_nautilus",
            Self::ZombieHorse => "zombie_horse",
            Self::SulfurCube => "sulfur_cube",
        }
    }
    pub fn skin(self) -> &'static str {
        match self {
            Self::Zombie => "zombie/zombie",
            Self::BabyZombie => "zombie/zombie_baby",
            Self::Husk => "zombie/husk",
            Self::BabyHusk => "zombie/husk_baby",
            Self::Drowned => "zombie/drowned",
            Self::BabyDrowned => "zombie/drowned_baby",
            Self::ZombieVillager => "zombie_villager/zombie_villager",
            Self::BabyZombieVillager => "zombie_villager/zombie_villager_baby",
            Self::Skeleton => "skeleton/skeleton",
            Self::Stray => "skeleton/stray",
            Self::Bogged => "skeleton/bogged",
            Self::Parched => "skeleton/parched",
            Self::WitherSkeleton => "skeleton/wither_skeleton",
            Self::Creeper => "creeper/creeper",
            Self::ChargedCreeper => "creeper/creeper",
            Self::Spider => "spider/spider",
            Self::CaveSpider => "spider/cave_spider",
            Self::Slime => "slime/slime",
            Self::MagmaCube => "slime/magmacube",
            Self::Enderman => "enderman/enderman",
            Self::Blaze => "blaze/blaze",
            Self::Breeze => "breeze/breeze",
            Self::Ghast => "ghast/ghast",
            Self::Phantom => "phantom/phantom",
            Self::Vex => "illager/vex",
            Self::Witch => "witch/witch",
            Self::Pillager => "illager/pillager",
            Self::Vindicator => "illager/vindicator",
            Self::Evoker => "illager/evoker",
            Self::Illusioner => "illager/illusioner",
            Self::Ravager => "illager/ravager",
            Self::Hoglin => "hoglin/hoglin",
            Self::BabyHoglin => "hoglin/hoglin_baby",
            Self::Zoglin => "hoglin/zoglin",
            Self::BabyZoglin => "hoglin/zoglin_baby",
            Self::Piglin => "piglin/piglin",
            Self::BabyPiglin => "piglin/piglin_baby",
            Self::PiglinBrute => "piglin/piglin_brute",
            Self::ZombifiedPiglin => "piglin/zombified_piglin",
            Self::BabyZombifiedPiglin => "piglin/zombified_piglin_baby",
            Self::Guardian => "guardian/guardian",
            Self::ElderGuardian => "guardian/guardian_elder",
            Self::Shulker => "shulker/shulker",
            Self::Silverfish => "silverfish/silverfish",
            Self::Endermite => "endermite/endermite",
            Self::Creaking => "creaking/creaking",
            Self::Warden => "warden/warden",
            Self::Dragon => "enderdragon/dragon",
            Self::Wither => "wither/wither",
            Self::Giant => "zombie/zombie",
            Self::KillerBunny => "rabbit/rabbit_caerbannog",
            Self::Bee => "bee/bee_angry",
            Self::Wolf => "wolf/wolf_angry",
            Self::PolarBear => "bear/polarbear",
            Self::Panda => "panda/panda_aggressive",
            Self::Llama => "llama/llama_brown",
            Self::TraderLlama => "llama/llama_creamy",
            Self::Goat => "goat/goat",
            Self::IronGolem => "iron_golem/iron_golem",
            Self::SnowGolem => "snow_golem/snow_golem",
            Self::Dolphin => "dolphin/dolphin",
            Self::Pufferfish => "fish/pufferfish",
            Self::CamelHusk => "camel/camel_husk",
            Self::ZombieNautilus => "nautilus/zombie_nautilus",
            Self::CoralZombieNautilus => "nautilus/zombie_nautilus_coral",
            Self::ZombieHorse => "horse/horse_zombie",
            Self::SulfurCube => "sulfur_cube/sulfur_cube_outer",
        }
    }
    pub fn sound_prefix(self) -> &'static str {
        match self {
            Self::Zombie => "zombie",
            Self::BabyZombie => "zombie",
            Self::Husk => "husk",
            Self::BabyHusk => "husk",
            Self::Drowned => "drowned",
            Self::BabyDrowned => "drowned",
            Self::ZombieVillager => "zombie_villager",
            Self::BabyZombieVillager => "zombie_villager",
            Self::Skeleton => "skeleton",
            Self::Stray => "stray",
            Self::Bogged => "bogged",
            Self::Parched => "parched",
            Self::WitherSkeleton => "wither_skeleton",
            Self::Creeper => "creeper",
            Self::ChargedCreeper => "creeper",
            Self::Spider => "spider",
            Self::CaveSpider => "spider",
            Self::Slime => "slime",
            Self::MagmaCube => "magma_cube",
            Self::Enderman => "enderman",
            Self::Blaze => "blaze",
            Self::Breeze => "breeze",
            Self::Ghast => "ghast",
            Self::Phantom => "phantom",
            Self::Vex => "vex",
            Self::Witch => "witch",
            Self::Pillager => "pillager",
            Self::Vindicator => "vindicator",
            Self::Evoker => "evoker",
            Self::Illusioner => "illusioner",
            Self::Ravager => "ravager",
            Self::Hoglin => "hoglin",
            Self::BabyHoglin => "hoglin",
            Self::Zoglin => "zoglin",
            Self::BabyZoglin => "zoglin",
            Self::Piglin => "piglin",
            Self::BabyPiglin => "piglin",
            Self::PiglinBrute => "piglin_brute",
            Self::ZombifiedPiglin => "zombified_piglin",
            Self::BabyZombifiedPiglin => "zombified_piglin",
            Self::Guardian => "guardian",
            Self::ElderGuardian => "elder_guardian",
            Self::Shulker => "shulker",
            Self::Silverfish => "silverfish",
            Self::Endermite => "endermite",
            Self::Creaking => "creaking",
            Self::Warden => "warden",
            Self::Dragon => "ender_dragon",
            Self::Wither => "wither",
            Self::Giant => "zombie",
            Self::KillerBunny => "rabbit",
            Self::Bee => "bee",
            Self::Wolf => "wolf",
            Self::PolarBear => "polar_bear",
            Self::Panda => "panda",
            Self::Llama => "llama",
            Self::TraderLlama => "llama",
            Self::Goat => "goat",
            Self::IronGolem => "iron_golem",
            Self::SnowGolem => "snow_golem",
            Self::Dolphin => "dolphin",
            Self::Pufferfish => "puffer_fish",
            Self::CamelHusk => "camel_husk",
            Self::ZombieNautilus => "zombie_nautilus",
            Self::CoralZombieNautilus => "zombie_nautilus",
            Self::ZombieHorse => "zombie_horse",
            Self::SulfurCube => "sulfur_cube",
        }
    }
    pub fn family(self) -> Family {
        match self {
            Self::Zombie => Family::Humanoid,
            Self::BabyZombie => Family::Humanoid,
            Self::Husk => Family::Humanoid,
            Self::BabyHusk => Family::Humanoid,
            Self::Drowned => Family::Humanoid,
            Self::BabyDrowned => Family::Humanoid,
            Self::ZombieVillager => Family::Illager,
            Self::BabyZombieVillager => Family::Illager,
            Self::Skeleton => Family::Humanoid,
            Self::Stray => Family::Humanoid,
            Self::Bogged => Family::Humanoid,
            Self::Parched => Family::Humanoid,
            Self::WitherSkeleton => Family::Humanoid,
            Self::Creeper => Family::Creeper,
            Self::ChargedCreeper => Family::Creeper,
            Self::Spider => Family::Spider,
            Self::CaveSpider => Family::Spider,
            Self::Slime => Family::Slime,
            Self::MagmaCube => Family::Slime,
            Self::Enderman => Family::TallHumanoid,
            Self::Blaze => Family::Blaze,
            Self::Breeze => Family::Breeze,
            Self::Ghast => Family::Ghast,
            Self::Phantom => Family::Phantom,
            Self::Vex => Family::Vex,
            Self::Witch => Family::Witch,
            Self::Pillager => Family::Illager,
            Self::Vindicator => Family::Illager,
            Self::Evoker => Family::Illager,
            Self::Illusioner => Family::Illager,
            Self::Ravager => Family::Ravager,
            Self::Hoglin => Family::Hoglin,
            Self::BabyHoglin => Family::Hoglin,
            Self::Zoglin => Family::Hoglin,
            Self::BabyZoglin => Family::Hoglin,
            Self::Piglin => Family::Humanoid,
            Self::BabyPiglin => Family::Humanoid,
            Self::PiglinBrute => Family::Humanoid,
            Self::ZombifiedPiglin => Family::Humanoid,
            Self::BabyZombifiedPiglin => Family::Humanoid,
            Self::Guardian => Family::Guardian,
            Self::ElderGuardian => Family::Guardian,
            Self::Shulker => Family::Shulker,
            Self::Silverfish => Family::Silverfish,
            Self::Endermite => Family::Silverfish,
            Self::Creaking => Family::Creaking,
            Self::Warden => Family::Warden,
            Self::Dragon => Family::Dragon,
            Self::Wither => Family::Wither,
            Self::Giant => Family::Humanoid,
            Self::KillerBunny => Family::Rabbit,
            Self::Bee => Family::Bee,
            Self::Wolf => Family::Quadruped,
            Self::PolarBear => Family::Quadruped,
            Self::Panda => Family::Quadruped,
            Self::Llama => Family::Mount,
            Self::TraderLlama => Family::Mount,
            Self::Goat => Family::Quadruped,
            Self::IronGolem => Family::Warden,
            Self::SnowGolem => Family::SnowGolem,
            Self::Dolphin => Family::Dolphin,
            Self::Pufferfish => Family::Guardian,
            Self::CamelHusk => Family::Mount,
            Self::ZombieNautilus => Family::Nautilus,
            Self::CoralZombieNautilus => Family::Nautilus,
            Self::ZombieHorse => Family::Mount,
            Self::SulfurCube => Family::Slime,
        }
    }
    pub fn health(self) -> f32 {
        match self {
            Self::Zombie => 100.00,
            Self::BabyZombie => 65.00,
            Self::Husk => 110.00,
            Self::BabyHusk => 65.00,
            Self::Drowned => 100.00,
            Self::BabyDrowned => 65.00,
            Self::ZombieVillager => 110.00,
            Self::BabyZombieVillager => 65.00,
            Self::Skeleton => 100.00,
            Self::Stray => 100.00,
            Self::Bogged => 90.00,
            Self::Parched => 100.00,
            Self::WitherSkeleton => 150.00,
            Self::Creeper => 100.00,
            Self::ChargedCreeper => 150.00,
            Self::Spider => 80.00,
            Self::CaveSpider => 70.00,
            Self::Slime => 65.00,
            Self::MagmaCube => 95.00,
            Self::Enderman => 200.00,
            Self::Blaze => 100.00,
            Self::Breeze => 150.00,
            Self::Ghast => 160.00,
            Self::Phantom => 100.00,
            Self::Vex => 70.00,
            Self::Witch => 130.00,
            Self::Pillager => 120.00,
            Self::Vindicator => 140.00,
            Self::Evoker => 180.00,
            Self::Illusioner => 160.00,
            Self::Ravager => 500.00,
            Self::Hoglin => 200.00,
            Self::BabyHoglin => 95.00,
            Self::Zoglin => 200.00,
            Self::BabyZoglin => 95.00,
            Self::Piglin => 110.00,
            Self::BabyPiglin => 65.00,
            Self::PiglinBrute => 250.00,
            Self::ZombifiedPiglin => 150.00,
            Self::BabyZombifiedPiglin => 75.00,
            Self::Guardian => 150.00,
            Self::ElderGuardian => 400.00,
            Self::Shulker => 150.00,
            Self::Silverfish => 40.00,
            Self::Endermite => 40.00,
            Self::Creaking => 300.00,
            Self::Warden => 2500.00,
            Self::Dragon => 2000.00,
            Self::Wither => 1800.00,
            Self::Giant => 600.00,
            Self::KillerBunny => 80.00,
            Self::Bee => 50.00,
            Self::Wolf => 100.00,
            Self::PolarBear => 200.00,
            Self::Panda => 160.00,
            Self::Llama => 130.00,
            Self::TraderLlama => 130.00,
            Self::Goat => 100.00,
            Self::IronGolem => 500.00,
            Self::SnowGolem => 50.00,
            Self::Dolphin => 75.00,
            Self::Pufferfish => 35.00,
            Self::CamelHusk => 180.00,
            Self::ZombieNautilus => 130.00,
            Self::CoralZombieNautilus => 140.00,
            Self::ZombieHorse => 150.00,
            Self::SulfurCube => 100.00,
        }
    }
    pub fn base_scale(self) -> f32 {
        match self {
            Self::Zombie => 1.00,
            Self::BabyZombie => 0.55,
            Self::Husk => 1.00,
            Self::BabyHusk => 0.55,
            Self::Drowned => 1.00,
            Self::BabyDrowned => 0.55,
            Self::ZombieVillager => 1.00,
            Self::BabyZombieVillager => 0.55,
            Self::Skeleton => 1.00,
            Self::Stray => 1.00,
            Self::Bogged => 1.00,
            Self::Parched => 1.00,
            Self::WitherSkeleton => 1.20,
            Self::Creeper => 1.00,
            Self::ChargedCreeper => 1.20,
            Self::Spider => 1.00,
            Self::CaveSpider => 0.70,
            Self::Slime => 2.00,
            Self::MagmaCube => 2.00,
            Self::Enderman => 1.00,
            Self::Blaze => 1.00,
            Self::Breeze => 1.00,
            Self::Ghast => 1.00,
            Self::Phantom => 1.20,
            Self::Vex => 1.00,
            Self::Witch => 1.00,
            Self::Pillager => 1.00,
            Self::Vindicator => 1.00,
            Self::Evoker => 1.00,
            Self::Illusioner => 1.00,
            Self::Ravager => 1.00,
            Self::Hoglin => 1.00,
            Self::BabyHoglin => 0.55,
            Self::Zoglin => 1.00,
            Self::BabyZoglin => 0.55,
            Self::Piglin => 1.00,
            Self::BabyPiglin => 0.55,
            Self::PiglinBrute => 1.00,
            Self::ZombifiedPiglin => 1.00,
            Self::BabyZombifiedPiglin => 0.55,
            Self::Guardian => 1.00,
            Self::ElderGuardian => 2.00,
            Self::Shulker => 1.00,
            Self::Silverfish => 1.00,
            Self::Endermite => 0.75,
            Self::Creaking => 1.00,
            Self::Warden => 1.00,
            Self::Dragon => 1.00,
            Self::Wither => 1.00,
            Self::Giant => 4.00,
            Self::KillerBunny => 1.00,
            Self::Bee => 1.00,
            Self::Wolf => 1.00,
            Self::PolarBear => 1.60,
            Self::Panda => 1.60,
            Self::Llama => 1.00,
            Self::TraderLlama => 1.00,
            Self::Goat => 1.00,
            Self::IronGolem => 1.05,
            Self::SnowGolem => 1.00,
            Self::Dolphin => 1.00,
            Self::Pufferfish => 0.70,
            Self::CamelHusk => 1.40,
            Self::ZombieNautilus => 1.00,
            Self::CoralZombieNautilus => 1.00,
            Self::ZombieHorse => 1.30,
            Self::SulfurCube => 2.00,
        }
    }
    pub fn texture_size(self) -> [f32; 2] {
        match self {
            Self::Zombie => [64.0, 64.0],
            Self::BabyZombie => [64.0, 64.0],
            Self::Husk => [64.0, 64.0],
            Self::BabyHusk => [64.0, 64.0],
            Self::Drowned => [64.0, 64.0],
            Self::BabyDrowned => [64.0, 64.0],
            Self::ZombieVillager => [64.0, 64.0],
            Self::BabyZombieVillager => [64.0, 64.0],
            Self::Skeleton => [64.0, 32.0],
            Self::Stray => [64.0, 32.0],
            Self::Bogged => [64.0, 32.0],
            Self::Parched => [64.0, 64.0],
            Self::WitherSkeleton => [64.0, 32.0],
            Self::Creeper => [64.0, 32.0],
            Self::ChargedCreeper => [64.0, 32.0],
            Self::Spider => [64.0, 32.0],
            Self::CaveSpider => [64.0, 32.0],
            Self::Slime => [64.0, 32.0],
            Self::MagmaCube => [64.0, 64.0],
            Self::Enderman => [64.0, 32.0],
            Self::Blaze => [64.0, 32.0],
            Self::Breeze => [32.0, 32.0],
            Self::Ghast => [128.0, 64.0],
            Self::Phantom => [64.0, 64.0],
            Self::Vex => [32.0, 32.0],
            Self::Witch => [64.0, 128.0],
            Self::Pillager => [64.0, 64.0],
            Self::Vindicator => [64.0, 64.0],
            Self::Evoker => [64.0, 64.0],
            Self::Illusioner => [64.0, 64.0],
            Self::Ravager => [128.0, 128.0],
            Self::Hoglin => [128.0, 64.0],
            Self::BabyHoglin => [64.0, 64.0],
            Self::Zoglin => [128.0, 64.0],
            Self::BabyZoglin => [64.0, 64.0],
            Self::Piglin => [64.0, 64.0],
            Self::BabyPiglin => [64.0, 64.0],
            Self::PiglinBrute => [64.0, 64.0],
            Self::ZombifiedPiglin => [64.0, 64.0],
            Self::BabyZombifiedPiglin => [64.0, 64.0],
            Self::Guardian => [64.0, 64.0],
            Self::ElderGuardian => [64.0, 64.0],
            Self::Shulker => [64.0, 64.0],
            Self::Silverfish => [64.0, 32.0],
            Self::Endermite => [64.0, 32.0],
            Self::Creaking => [64.0, 64.0],
            Self::Warden => [128.0, 128.0],
            Self::Dragon => [256.0, 256.0],
            Self::Wither => [64.0, 64.0],
            Self::Giant => [64.0, 64.0],
            Self::KillerBunny => [64.0, 64.0],
            Self::Bee => [64.0, 64.0],
            Self::Wolf => [64.0, 32.0],
            Self::PolarBear => [128.0, 64.0],
            Self::Panda => [64.0, 64.0],
            Self::Llama => [128.0, 64.0],
            Self::TraderLlama => [128.0, 64.0],
            Self::Goat => [64.0, 64.0],
            Self::IronGolem => [128.0, 128.0],
            Self::SnowGolem => [64.0, 64.0],
            Self::Dolphin => [64.0, 64.0],
            Self::Pufferfish => [32.0, 32.0],
            Self::CamelHusk => [128.0, 128.0],
            Self::ZombieNautilus => [128.0, 128.0],
            Self::CoralZombieNautilus => [128.0, 128.0],
            Self::ZombieHorse => [64.0, 64.0],
            Self::SulfurCube => [128.0, 128.0],
        }
    }
    pub fn flying(self) -> bool {
        matches!(
            self,
            Self::Blaze
                | Self::Breeze
                | Self::Ghast
                | Self::Phantom
                | Self::Vex
                | Self::Guardian
                | Self::ElderGuardian
                | Self::Dragon
                | Self::Wither
                | Self::Bee
                | Self::Dolphin
                | Self::ZombieNautilus
                | Self::CoralZombieNautilus
        )
    }
    pub fn ranged(self) -> bool {
        matches!(
            self,
            Self::Drowned
                | Self::Skeleton
                | Self::Stray
                | Self::Bogged
                | Self::Parched
                | Self::Blaze
                | Self::Breeze
                | Self::Ghast
                | Self::Witch
                | Self::Pillager
                | Self::Evoker
                | Self::Illusioner
                | Self::Piglin
                | Self::Guardian
                | Self::ElderGuardian
                | Self::Shulker
                | Self::Warden
                | Self::Dragon
                | Self::Wither
                | Self::Llama
                | Self::TraderLlama
                | Self::SnowGolem
        )
    }
    pub fn explosive(self) -> bool {
        matches!(
            self,
            Self::Creeper | Self::ChargedCreeper | Self::SulfurCube
        )
    }
    pub fn boss(self) -> bool {
        matches!(self, Self::Dragon | Self::Wither | Self::Warden)
    }
    pub fn dimensions(self) -> (f32, f32) {
        match self.family() {
            Family::Spider => (26.0, 34.0),
            Family::Slime => (18.0, 36.0),
            Family::TallHumanoid => (13.0, 108.0),
            Family::Dragon => (85.0, 110.0),
            Family::Wither => (28.0, 120.0),
            Family::Ghast => (65.0, 140.0),
            Family::Guardian | Family::Nautilus => (22.0, 40.0),
            Family::Silverfish | Family::Rabbit => (10.0, 22.0),
            Family::Vex | Family::Bee => (10.0, 28.0),
            Family::Phantom | Family::Dolphin => (24.0, 25.0),
            Family::Quadruped | Family::Hoglin => (22.0, 48.0),
            Family::Ravager => (36.0, 90.0),
            Family::Mount => (24.0, 90.0),
            Family::Warden | Family::Creaking => (22.0, 108.0),
            _ => (12.0, 70.0),
        }
    }
    pub fn speed(self) -> f32 {
        match self.family() {
            Family::Spider => 145.0,
            Family::Silverfish => 155.0,
            Family::TallHumanoid => 175.0,
            Family::Creeper => 100.0,
            Family::Slime => 85.0,
            Family::Warden => 105.0,
            _ => 110.0,
        }
    }
    pub fn flight_height(self) -> f32 {
        match self {
            Self::Dragon => 500.0,
            Self::Wither => 280.0,
            Self::Ghast => 350.0,
            Self::Phantom => 230.0,
            Self::Blaze => 110.0,
            Self::Vex => 100.0,
            Self::Bee => 60.0,
            _ => 32.0,
        }
    }
    pub fn damage(self) -> i32 {
        if self.boss() {
            28
        } else if matches!(self, Self::Ravager | Self::PiglinBrute | Self::Enderman) {
            22
        } else {
            12
        }
    }
}
