macro_rules! spans {
    ($callback:ident) => {
        $callback! {
            FixedTocAdvance {
                ordinal: 0,
                name: "Advance",
                track: "span.Advance",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocBookkeeping {
                ordinal: 1,
                name: "Bookkeeping",
                track: "span.Bookkeeping",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocFanout {
                ordinal: 2,
                name: "Fanout",
                track: "span.Fanout",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocGather {
                ordinal: 3,
                name: "Gather",
                track: "span.Gather",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocIngress {
                ordinal: 4,
                name: "Ingress",
                track: "span.Ingress",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocSnapshot {
                ordinal: 5,
                name: "Snapshot",
                track: "span.Snapshot",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FixedTocStep {
                ordinal: 6,
                name: "Step",
                track: "span.Step",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FramesDiagMs {
                ordinal: 7,
                name: "Diag",
                track: "span.Diag",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FramesEffectsMs {
                ordinal: 8,
                name: "Effects",
                track: "span.Effects",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FramesFixedMs {
                ordinal: 9,
                name: "FixedUpdate",
                track: "span.FixedUpdate",
                category: "iw4l.sim",
                coverage_root: true,
            },
            FramesPostupdateMs {
                ordinal: 10,
                name: "PostUpdate",
                track: "span.PostUpdate",
                category: "iw4l.frame",
                coverage_root: true,
            },
            FramesPredictMs {
                ordinal: 11,
                name: "Predict",
                track: "span.Predict",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FramesPresentMs {
                ordinal: 12,
                name: "Present",
                track: "span.Present",
                category: "iw4l.sim",
                coverage_root: false,
            },
            FramesPreupdateMs {
                ordinal: 13,
                name: "PreUpdate",
                track: "span.PreUpdate",
                category: "iw4l.frame",
                coverage_root: true,
            },
            FramesUpdateMs {
                ordinal: 14,
                name: "Update",
                track: "span.Update",
                category: "iw4l.sim",
                coverage_root: true,
            },
            FramesWallFrameMs {
                ordinal: 15,
                name: "wall",
                track: "span.wall",
                category: "iw4l.frame",
                coverage_root: false,
            },
            HostFxPresentCpuMs {
                ordinal: 16,
                name: "fx_present",
                track: "span.fx_present",
                category: "iw4l.fx",
                coverage_root: false,
            },
            HostFxUpdateCpuMs {
                ordinal: 17,
                name: "fx_update",
                track: "span.fx_update",
                category: "iw4l.fx",
                coverage_root: false,
            },
            HostPostExecuteMs {
                ordinal: 18,
                name: "post_execute",
                track: "span.post_execute",
                category: "iw4l.render",
                coverage_root: false,
            },
            HostPostRebuildMs {
                ordinal: 19,
                name: "post_rebuild",
                track: "span.post_rebuild",
                category: "iw4l.render",
                coverage_root: false,
            },
            HostSkinModelMs {
                ordinal: 20,
                name: "skin_model",
                track: "span.skin_model",
                category: "iw4l.render",
                coverage_root: false,
            },
            HostStaticSunFxMs {
                ordinal: 21,
                name: "static_sun_fx",
                track: "span.static_sun_fx",
                category: "iw4l.render",
                coverage_root: false,
            },
            HostStaticSunMs {
                ordinal: 22,
                name: "static_sun",
                track: "span.static_sun",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderColourPrepareMs {
                ordinal: 23,
                name: "colour_prepare",
                track: "span.colour_prepare",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderColourSubmitMs {
                ordinal: 24,
                name: "colour_submit",
                track: "span.colour_submit",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderCullCpuMs {
                ordinal: 25,
                name: "cull",
                track: "span.cull",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderPrepareCameraMs {
                ordinal: 26,
                name: "prepare_camera",
                track: "span.prepare_camera",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderPrepareShadowMs {
                ordinal: 27,
                name: "prepare_shadow",
                track: "span.prepare_shadow",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderReceiveWorldMs {
                ordinal: 28,
                name: "receive_render_world",
                track: "span.receive_render_world",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderExtractBodyMs {
                ordinal: 29,
                name: "extract_body",
                track: "span.extract_body",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderDispatchWorldMs {
                ordinal: 30,
                name: "dispatch_render_world",
                track: "span.dispatch_render_world",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderRenderRenderMs {
                ordinal: 31,
                name: "render_render",
                track: "span.render_render",
                category: "iw4l.render",
                coverage_root: false,
            },
            RenderRenderThreadMs {
                ordinal: 32,
                name: "render_thread",
                track: "span.render_thread",
                category: "iw4l.render",
                coverage_root: true,
            },
            TocInput {
                ordinal: 33,
                name: "Input",
                track: "span.Input",
                category: "iw4l.sim",
                coverage_root: false,
            },
            TocLoad {
                ordinal: 34,
                name: "Load",
                track: "span.Load",
                category: "iw4l.sim",
                coverage_root: false,
            },
            TocReceive {
                ordinal: 35,
                name: "Receive",
                track: "span.Receive",
                category: "iw4l.sim",
                coverage_root: false,
            },
            TocReconcile {
                ordinal: 36,
                name: "Reconcile",
                track: "span.Reconcile",
                category: "iw4l.sim",
                coverage_root: false,
            },
            TocSend {
                ordinal: 37,
                name: "Send",
                track: "span.Send",
                category: "iw4l.sim",
                coverage_root: false,
            },
            TocUi {
                ordinal: 38,
                name: "Ui",
                track: "span.Ui",
                category: "iw4l.sim",
                coverage_root: false,
            },
        }
    };
}
pub(crate) use spans;

macro_rules! counters {
    ($callback:ident) => {
        $callback! {
        CounterBindGroup0 {
            ordinal: 0,
            name: "bind0",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterBindGroup1 {
            ordinal: 1,
            name: "bind1",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterCmdState {
            ordinal: 2,
            name: "cmd_state",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterMultiDraws {
            ordinal: 3,
            name: "multi_draw",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterMultiDrawCommands {
            ordinal: 4,
            name: "multi_draw_cmds",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterDipsColour {
            ordinal: 5,
            name: "dip_colour",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterDipsSun {
            ordinal: 6,
            name: "dip_sun",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterDraws {
            ordinal: 7,
            name: "draws",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterFxElemAllocFail {
            ordinal: 8,
            name: "fx_elem_alloc_fail",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.fx",
            category_class: explicit,
        },
        CounterFxElemLive {
            ordinal: 9,
            name: "fx_elem_live",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.fx",
            category_class: explicit,
        },
        CounterProcessAllocations {
            ordinal: 10,
            name: "process_allocations",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        CounterSubmittedBatches {
            ordinal: 11,
            name: "batches",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGraphRenderMs {
            ordinal: 12,
            name: "graph_render",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// The wall between the last system of the render graph's `Render` set and
        /// the first of its `Finish` set: bevy's `submit_pending_command_buffers`
        /// — which finishes every pending encoder *and* calls `Queue::submit` —
        /// plus `handle_uncovered_swap_chains`, plus whatever the executor ran in
        /// the gaps. Not a `Queue::submit` body, and not addable to anything.
        RenderGraphSubmitIntervalMs {
            ordinal: 13,
            name: "graph_submit_schedule_interval",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Command buffers and unfinished encoders waiting when that interval
        /// began: what the one number above had to finish and submit.
        RenderGraphSubmitPendingN {
            ordinal: 14,
            name: "graph_submit_pending",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGraphPresentMs {
            ordinal: 15,
            name: "graph_present",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// How long the state this render frame drew had been extracted by the
        /// time the render graph finished with it, and how many main frames the
        /// main world had opened since. Zero frames behind is a render world
        /// running in line with the main one; one or more is a pipelined render
        /// world drawing an older state. Neither is input-to-photon: it stops
        /// where the graph does, one step before the present call, and the
        /// compositor and the display are further outside still.
        RenderPresentedStateAgeMs {
            ordinal: 16,
            name: "presented_state_age",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderPresentedFramesBehind {
            ordinal: 17,
            name: "presented_frames_behind",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Code-constant writes the material overlay made for the colour list.
        /// Work the frame did to fill values a shader may or may not read; it
        /// falls when a run knows what its shell reads before filling them.
        CounterOverlayConstWrites {
            ordinal: 18,
            name: "overlay_const_writes",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderSubmitSunMs {
            ordinal: 19,
            name: "submit_sun",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderSubmitGatherMs {
            ordinal: 20,
            name: "submit_gather",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderSubmitPrepareMs {
            ordinal: 21,
            name: "submit_prepare",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderSubmitArenaMs {
            ordinal: 22,
            name: "submit_arena",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        RenderSubmitRecordMs {
            ordinal: 23,
            name: "submit_record",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        PresentPublishMs {
            ordinal: 24,
            name: "present_publish",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        HudSurfacesScheduleMs {
            ordinal: 25,
            name: "hud_surfaces_schedule_interval",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        HudStageMaxScheduleMs {
            ordinal: 26,
            name: "hud_stage_max_schedule_interval",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        HudTessBodyMs {
            ordinal: 27,
            name: "hud_tess_body",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        HudTessJobs {
            ordinal: 28,
            name: "hud_tess_jobs",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        UiHudSetupMs {
            ordinal: 29,
            name: "ui_hud_setup",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        UiApplyDeferredMs {
            ordinal: 30,
            name: "ui_apply_deferred",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        UiHudVisibilityMs {
            ordinal: 31,
            name: "ui_hud_visibility",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        HudStageMaxScheduleAt {
            ordinal: 32,
            name: "hud_stage_max_schedule_interval_at",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.frame",
            category_class: explicit,
        },
        RenderGpuColourMs {
            ordinal: 33,
            name: "gpu_colour",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGpuSunMs {
            ordinal: 34,
            name: "gpu_sun",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGpuSpotMs {
            ordinal: 35,
            name: "gpu_spot",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGpuFloatzMs {
            ordinal: 36,
            name: "gpu_floatz",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGpuPostfxMs {
            ordinal: 37,
            name: "gpu_postfx",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        RenderGpuFrameMs {
            ordinal: 38,
            name: "gpu_frame",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        SpotShadowGpu {
            ordinal: 39,
            name: "spot_shadow_gpu",
            unit: Count,
            unit_class: default,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        SpotShadowGpuMiss {
            ordinal: 40,
            name: "spot_shadow_gpu_miss",
            unit: Count,
            unit_class: default,
            origin: Gpu,
            origin_class: explicit,
            category: "iw4l.render",
            category_class: default,
        },
        SpotShadowSlotN {
            ordinal: 41,
            name: "spot_shadow_slot_n",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        XmodelColourCameraFrustum {
            ordinal: 42,
            name: "xmodel_colour_camera_frustum",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        XmodelColourNoLighting {
            ordinal: 43,
            name: "xmodel_colour_no_lighting",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        XmodelLayoutOverlay {
            ordinal: 44,
            name: "xmodel_layout_overlay",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        FxLayoutOverlay {
            ordinal: 45,
            name: "fx_layout_overlay",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        WorldPretessSkip {
            ordinal: 46,
            name: "world_pretess_skip",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        SmodelIbSkip {
            ordinal: 47,
            name: "smodel_ib_skip",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Bevy `PrepareViews` set as a wall interval: the render systems between
        /// `Specialize` and `Queue` ran inside it, and so did whatever else the
        /// executor scheduled there. A body only in the sense the HUD bodies are —
        /// read it against the schedule gaps, never as exclusive CPU work.
        RenderPrepareViewsMs {
            ordinal: 48,
            name: "prepare_views",
            unit: Milliseconds,
            unit_class: explicit,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Constant-arena upload census, taken where the upload is chosen and
        /// performed. Byte counts are CPU-side staging sizes; the driver copies
        /// them to the device after the call returns.
        CounterArenaUsedBytes {
            ordinal: 49,
            name: "arena_used_bytes",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaCapacityBytes {
            ordinal: 50,
            name: "arena_capacity_bytes",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaDirtyBytes {
            ordinal: 51,
            name: "arena_dirty_bytes",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaUploadedBytes {
            ordinal: 52,
            name: "arena_uploaded_bytes",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaUploadCalls {
            ordinal: 53,
            name: "arena_upload_calls",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Full uploads grouped by reason: the GPU buffer was recreated, or an
        /// explicit owner/generation/reservation reset required it. A changed
        /// logical length alone is not a reason — the tail uploads on its own.
        CounterArenaFullResize {
            ordinal: 54,
            name: "arena_full_resize",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaFullFlag {
            ordinal: 55,
            name: "arena_full_flag",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterArenaReallocN {
            ordinal: 56,
            name: "arena_realloc",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        /// Postfx submit decision: the refusal discriminant (no strings per
        /// frame), and the planned/executed step counts with the frame identity
        /// held at the decision point.
        CounterPostFxRefusal {
            ordinal: 57,
            name: "postfx_refusal",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterPostFxPlannedSteps {
            ordinal: 58,
            name: "postfx_planned_steps",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        CounterPostFxExecutedSteps {
            ordinal: 59,
            name: "postfx_executed_steps",
            unit: Count,
            unit_class: default,
            origin: Cpu,
            origin_class: default,
            category: "iw4l.render",
            category_class: default,
        },
        }
    };
}
pub(crate) use counters;
